version: '3.9'
services:
  nginxpm:
    container_name: nginxPM
    image: jc21/nginx-proxy-manager:latest
    restart: always
    volumes:
      - ./data/data:/data
      - ./data/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
      - 81:81
    environment:
      TZ: "Europe/PARIS"
      DB_SQLITE_FILE: "/data/database.sqlite"